# WARNING - Generated by {fusen} from /dev/estimate_overlap_bias.Rmd: do not edit by hand

test_that("estimate_overlap_bias works", {
  res_df_bin <- estimate_overlap_bias(
    samplesize_exposure = 361194,
    samplesize_outcome = 1125328,
    case_prop = 0.035,
    rsq_exposure = 0.068,
    n_variants = 196,
    ols_bias = 0.2,
    overlap_prop = 0.3
  )

  res_df_continuous <- estimate_overlap_bias(
    samplesize_exposure = 361194,
    samplesize_outcome = 1125328,
    rsq_exposure = 0.068,
    n_variants = 196,
    ols_bias = 0.2,
    overlap_prop = 0.3
  )
  
  res_df_expf <- estimate_overlap_bias(
    samplesize_exposure = 361194,
    samplesize_outcome = 1125328,
    exp_f = 134,
    rsq_exposure = 0.068,
    n_variants = 196,
    ols_bias = 0.2,
    overlap_prop = 0.3
  )

  expect_equal(nrow(res_df_bin), 1)
  expect_equal(ncol(res_df_bin), 2)
  expect_equal(nrow(res_df_continuous), 1)
  expect_equal(ncol(res_df_continuous), 2)
  expect_equal(nrow(res_df_expf), 1)
  expect_equal(ncol(res_df_expf), 2)
})
