# WARNING - Generated by {fusen} from /dev/estimate_overlap_bias.Rmd: do not edit by hand

test_that("estimate_f_lci95 works", {
  expect_true(inherits(estimate_f_lci95, "function"))
  expect_type(estimate_f_lci95(134, 196, 361194), "double")
})
