# WARNING - Generated by {fusen} from /dev/estimate_overlap_bias.Rmd: do not edit by hand

#' Estimate F-statistic
#'
#' @param samplesize_exposure (numeric) Sample size of population used to define genetic instrument for the exposure of interest
#' @param n_variants (numeric) Number of genetic variants included in genetic instrument for the exposure of interest
#' @param rsq_exposure (numeric) R^2^ value (coefficient of determination) of genetic instrument for the exposure of interest; used to estimate
#' @param lci_95 (logical; default = FALSE) If TRUE, the function will return the lower limit of the one-sided 95% confidence interval of the F-statistic, which may represent a more conservative/less optimistic estimate
#'
#' @return Numeric vector containing the estimated F-statistic
#' @export
#'

#' @examples
#' estimate_f(samplesize_exposure = 361194, n_variants = 196, rsq_exposure = 0.068, lci_95 = FALSE)
#' 
#' # return lower bound of one-sided 95% confidence interval of F-statistic
#' estimate_f(samplesize_exposure = 361194, n_variants = 196, rsq_exposure = 0.068, lci_95 = TRUE)
estimate_f <- function(samplesize_exposure, n_variants, rsq_exposure, lci_95 = FALSE) {
  expf <- (samplesize_exposure - n_variants - 1) / n_variants * rsq_exposure / (1 - rsq_exposure)

  if (lci_95) {
    expf <- estimate_f_lci95(expf, n_variants, samplesize_exposure)
  }

  return(expf)
}

#' Estimate the lower limit of the one-sided 95% confidence interval of an F-statistic
#'
#' @return Numeric vector containing the estimated F-statistic
#' @importFrom stats pf
#' @noRd
estimate_f_lci95 <- function(f, nu1, nu2) {
  lambda <- f * nu1 * (nu2 - 2) / nu2 - nu1
  lower <- f - 1
  while (pf(lower, df1 = nu1, df2 = nu2, ncp = lambda) > 0.05) {
    lower <- lower - 1
  }
  upper <- lower + 1
  while (abs(pf((lower + upper) / 2, df1 = nu1, df2 = nu2, ncp = lambda) - 0.05) > 0.0001) {
    if (pf((lower + upper) / 2, df1 = nu1, df2 = nu2, ncp = lambda) > 0.05) {
      upper <- (lower + upper) / 2
    }
    if (pf((lower + upper) / 2, df1 = nu1, df2 = nu2, ncp = lambda) < 0.05) {
      lower <- (lower + upper) / 2
    }
  }
  return((lower + upper) / 2)
}
