# WARNING - Generated by {fusen} from /dev/estimate_overlap_bias.Rmd: do not edit by hand

#' Estimate the lower limit of the one-sided 95% confidence interval of an F-statistic
#'
#' @return Numeric vector containing the estimated F-statistic
#'
#' @noRd
#' @examples
#' \dontrun{
#' estimate_f_lci95(134, 196, 361194)
#' }
estimate_f_lci95 <- function(f, nu1, nu2) {
  lambda <- f * nu1 * (nu2 - 2) / nu2 - nu1
  lower <- f - 1
  while (pf(lower, df1 = nu1, df2 = nu2, ncp = lambda) > 0.05) {
    lower <- lower - 1
  }
  upper <- lower + 1
  while (abs(pf((lower + upper) / 2, df1 = nu1, df2 = nu2, ncp = lambda) - 0.05) > 0.0001) {
    if (pf((lower + upper) / 2, df1 = nu1, df2 = nu2, ncp = lambda) > 0.05) {
      upper <- (lower + upper) / 2
    }
    if (pf((lower + upper) / 2, df1 = nu1, df2 = nu2, ncp = lambda) < 0.05) {
      lower <- (lower + upper) / 2
    }
  }
  return((lower + upper) / 2)
}
